# Generated by Django 3.1.9 on 2021-12-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Sdktype',
            field=models.IntegerField(max_length=10),
        ),
    ]
