# Generated by Django 3.1.9 on 2021-12-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211207_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Sdktype',
            field=models.IntegerField(blank=True),
        ),
    ]
