# Generated by Django 3.0.9 on 2021-12-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20211213_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
