# Generated by Django 3.0.9 on 2022-01-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_last_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
