# Generated by Django 3.0.9 on 2021-12-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=250)),
                ('country', models.IntegerField()),
                ('active', models.IntegerField()),
                ('logo', models.ImageField(default='Picture', upload_to='pro/pictures')),
            ],
        ),
    ]
