# Generated by Django 3.0.9 on 2021-12-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectforprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectforprofile',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='projectforprofile',
            old_name='project_id',
            new_name='project',
        ),
    ]
