# Generated by Django 3.0.9 on 2022-01-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_auto_20220107_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='registerDate',
            field=models.DateField(),
        ),
    ]
