# Generated by Django 3.0.9 on 2022-01-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_auto_20220117_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='project',
            field=models.IntegerField(),
        ),
    ]
